version: "3.10"

services:
  ml-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: ml-api
    ports:
      - "80:80"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - ml-api