version: "3.10"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-service
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "8501:8501"
    depends_on:
      - api