FROM python:3.10
WORKDIR /

COPY app/api/requirements-api.txt ./requirements.txt
COPY app/api/ ./app/api/
COPY app/model/ ./app/model/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.api.model-api:app", "--host", "0.0.0.0", "--port", "80"]