FROM python:3.10
WORKDIR /

COPY app/requirements-frontend.txt ./requirements.txt
COPY app/App.py ./app/App.py
COPY app/pages/ ./app/pages/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app/App.py", "--server.port=8501", "--server.address=0.0.0.0"]